### ISSUE TITLE
Node 18でも大丈夫そうです

### ISSUE THREAD

**Issue by sengokyu** [yasudacloud/strapi-plugin-ja-pack#4]
こんにちは
package.json には、node のバージョン上限の記述があります。
自分の環境は node 18 ですが、動作には問題なさそうなので、18 でもよさそうです。

```json
{
  /* (snip) */
  "engines": {
    "node": ">=12.x. <=16.x.x",
    "npm": ">=6.0.0"
  }
}
```

自分の環境です。
* node v18.1.2
* strap 4.9.0
* kubuntu 22.04

よろしくお願いします

**Comment by yasudacloud** [comment]
@sengokyu 
ご報告ありがとうございます。
近々NodeJS18対応版を出すように致します。

このプラグインを作った当時にStrapiが18をサポートしておらず、他のプラグインのpackage.jsonを参考に記述したという経緯でした。

**Comment by yasudacloud** [comment]
@sengokyu 
1.0.3をnpmに公開しました。
https://www.npmjs.com/package/strapi-plugin-ja-pack

バージョン指定はStrapi本体と合わせています。
https://github.com/strapi/strapi/blob/main/package.json#L105

どうもありがとうございましたm(__)m
